language: php

php:
  - 7.1
  - 7.2
  - 7.3

cache:
  directories:
    - "$HOME/.composer/cache/files"

env:
  matrix:
    - COMPOSER_FLAGS=""

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - composer test:basic

after_success:
  - bash <(curl -s https://codecov.io/bash)